name: dental-landmarks
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - simpleitk
  - nibabel
  - pillow
  - pyqt=5
  - tqdm
  - opencv
  - pytorch
  - torchvision
  - jupyter
  - pip
  - pip:
    - ultralytics
